output "alb_dns_name" {
  description = "DNS name of the Application Load Balancer"
  value       = aws_lb.this.dns_name
}

# output "ecs_cluster_name" {
#   description = "Name of the ECS cluster"
#   value       = aws_ecs_cluster.this.name
# }

output "rds_endpoint" {
  description = "RDS MySQL endpoint"
  value       = aws_db_instance.this.address
}

output "rds_secret_arn" {
  description = "ARN of the Secrets Manager secret generated by RDS"
  value       = aws_db_instance.this.master_user_secret[0].secret_arn
}

output "efs_id" {
  description = "ID of the EFS file system"
  value       = aws_efs_file_system.this.id
}

output "ecs_tasks_sg_id" {
  description = "Security group ID of the ECS tasks"
  value       = aws_security_group.ecs_tasks.id
}